version: '3.5'

services:
  angular-service:
    container_name: tms-container1
    build: ./
    volumes:
    - './:/usr/src/app'
    ports:
    - "4201:4200"
    command: >
      bash -c "npm start"
